[package]
name = "fopro"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
hyper = { version = "1.4.1", features = ["http1", "http2", "server"] }
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
